### PR TITLE
BP-2912 Rename IDin to iDin to prevent errors in Linux systems

### PR DESCRIPTION
**Pull request by roelvanhintum**
Followup on #141

### CODE REVIEW

**Comment by roelvanhintum** [comment]
@ShuCh3n can you take a look at this?

**Comment by ShuCh3n** [comment]
Isn't this issue already merge in this PR #145

**Comment by roelvanhintum** [comment]
Yes, i see. Thanks! Is there any ETA on the release?

**Comment by ShuCh3n** [comment]
I just did a release for this https://github.com/buckaroo-it/BuckarooSDK_PHP/releases/tag/1.8.1

**Pull request closed without merging**
