### PR TITLE
Reduce guzzlehttp/guzzle version requirement to 6

### PR DESCRIPTION
**Pull request by reflie-nxte**
Hi. During working with this SDK I noticed that it requires a guzzle of version 7. However, our project is locked to guzzle 6 and we cannot upgrade it for now due to other dependencies. That's why I created a fork of this repo and reduced the requirement to guzzle 6. I did test everything and integration works great on this version. That's why I'm asking to change the version requirement in the main repo.

### CODE REVIEW

**Comment by ShuCh3n** [comment]
We need to run unit tests for this change. In the future, we will completely remove the guzzle package. Please keep that in mind.

**Comment by bohdan-hlamazda** [comment]
> We need to run unit tests for this change. In the future, we will completely remove the guzzle package. Please keep that in mind.

What you are going to use instead?

**Comment by ShuCh3n** [comment]
@bohdan-hlamazda Well, it will check if the project contains guzzle package. If guzzle is installed in the project it will use guzzle, otherwise it will use curl as fallback.

**Comment by avido** [comment]
> We need to run unit tests for this change. In the future, we will completely remove the guzzle package. Please keep that in mind.

Why would you remove guzzle ??

**Comment by ShuCh3n** [comment]
@reflie-nxte Not yet we are still working on a version without guzzle

**Comment by avido** [comment]
Still unclear why guzzle should be removed. As Guzzle really has some benefits over just cURL...

**Comment by ShuCh3n** [comment]
It's not that we are going to remove the support of guzzle. We are not going to depend on guzzle. In case guzzle isn't available in a project, it can still work by relying on curl.

**Comment by Buckaroo-Rens** [comment]
@avido I think it's mainly about making things more flexible. Removing hard dependencies on specific versions etc.

**Comment by ShuCh3n** [comment]
> > It's not that we are going to remove the support of guzzle. We are not going to depend on guzzle. In case guzzle isn't available in a project, it can still work by relying on curl.
> 
> Okay so basically you're saying you're gonna have code duplication ?

Well not really, just multiple ways to handle the calls.

**Pull request closed without merging**
